server:
  #https加密端口号 443
  port: 443

  ssl:
    key-store: classpath:chenweiyuan.jks
    #SSL证书密码
    key-store-password: r1co3u3418t1o
    #证书类型
    key-store-type: JKS

      servlet:
        context-path: /diancan
    spring:
      datasource:
        url: jdbc:mysql://119.23.232.220:3306/ljh_online_education?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        hikari:
          connection-init-sql: set names utf8mb4
        tomcat:
          init-s-q-l: SET NAMES utf8mb4 #这是最重要的一步
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: update

