server:
  #https加密端口号 443
  port: 443

  ssl:
    key-store: classpath:chenweiyuan.jks
    #SSL证书密码
    key-store-password: r1co3u3418t1o
    #证书类型
    key-store-type: JKS

      servlet:
        context-path: /diancan
    spring:
      datasource:
        url: jdbc:mysql://localhost/diancan?characterEncoding=utf-8&useSSL=false&serverTimeZone=UTC
          &useOldAliasMetadataBehavior=true&allowPublicKeyRetrieval=true
        username: root
        password: 123
        hikari:
          connection-init-sql: set names utf8mb4
        tomcat:
          init-s-q-l: SET NAMES utf8mb4 #这是最重要的一步
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: update

